### PR TITLE
fixed cookies problem

### PR DESCRIPTION
**Pull request by KSemenenko**
hi, I was mistaken)
after .net 4.5 the project didn't become compatible to unity 3d, for example .
so, I rolled away all the changes, returned on a step backwards.
now please force push in the master from this request

it is your old code on .net 2.0 with fix cookies

sorry)

### CODE REVIEW

**Comment by pierredavidbelanger** [comment]
This pull request can not be merged. And I will not force push it.

Instead, I reverted commit c92f363d0638d03750000729dfb534fe86a5a488 in commit db252c7ac8ab569800543b3522cc58e5c0c2608d.

Are you able to issue this PR again, but on top of the master branch please ?

**Comment by pierredavidbelanger** [comment]
Oh, from what I see, I should already be able merge this PR as is.
Gotta love GIT!

**Comment by pierredavidbelanger** [comment]
Done, thank you!

**Comment by KSemenenko** [comment]
thank you too!

**Pull request merged**
