### PR TITLE
Added WinRT support

### PR DESCRIPTION
**Pull request by LoveMetal-StrangeGames**
Now on top of your original project. :)

### CODE REVIEW

**Comment by pierredavidbelanger** [comment]
I wonder why the need for a copy/paste from dotnet/ChatterBotAPI to dotnet/ChatterBotAPI-WinRT ?
Are your changes incompatible with the current dotnet/ChatterBotAPI version ?

**Comment by LoveMetal-StrangeGames** [comment]
Yes, some namespaces as Microsoft.Xaml.UI are not  standard .NET. But I can't check if I can't do some conditionnal compilation to keep my changes to  dotnet/ChatterBotAPI
________________________________
De : Pierre-David Bélanger<mailto:notifications@github.com>
Envoyé : ‎26/‎08/‎2015 17:48
À : pierredavidbelanger/chatter-bot-api<mailto:chatter-bot-api@noreply.github.com>
Cc : Antoine Champion<mailto:antoine-_-champion@hotmail.fr>
Objet : Re: [chatter-bot-api] Added WinRT support (#17)

I wonder why the need for a copy/paste from dotnet/ChatterBotAPI to dotnet/ChatterBotAPI-WinRT ?
Are your changes incompatible with the current dotnet/ChatterBotAPI version ?

---

**Comment by pierredavidbelanger** [comment]
I do not see `Microsoft.Xaml.UI` anywhere in my code.
And I do not think I need it. Can you point me where you see it, maybe I can just get rid of this.

One diff I can see is that you replaced the `XPathSearch` method implementation with an hardcoded `Regex.Match`. So the `System.Xml.XPath` is not available on WinRT ?

Also, I see that you made a couple methods `async`. I would prefer the library to stay synchronous, and let the application layer be responsible to call the lib asynchronously.

**Comment by LoveMetal-StrangeGames** [comment]
I spoke of Microsoft.Xaml.UI because it was the first example which came to my mind but I'll check if there are uncompatible namespace, because there still are some.

XPath isn't advailable on WinRT, and a regex was the simplest replacement to me.

Methods I made async need to be like this because of file access in WinRT. To be completly sync, we would need to make a method which parse the file content provided as a string in argument, and it would be the user who would do the file handling himself.
________________________________
De : Pierre-David Bélanger<mailto:notifications@github.com>
Envoyé : ‎26/‎08/‎2015 18:21
À : pierredavidbelanger/chatter-bot-api<mailto:chatter-bot-api@noreply.github.com>
Cc : Antoine Champion<mailto:antoine-_-champion@hotmail.fr>
Objet : Re: [chatter-bot-api] Added WinRT support (#17)

I do not see `Microsoft.Xaml.UI` anywhere in my code.
And I do not think I need it. Can you point me where you see it, maybe I can just get rid of this.

One diff I can see is that you replaced the `XPathSearch` method implementation with an hardcoded `Regex.Match`. So the `System.Xml.XPath` is not available on WinRT ?

Also, I see that you made a couple methods `async`. I would prefer the library to stay synchronous, and let the application layer be responsible to call the lib asynchronously.

---

**Comment by pierredavidbelanger** [comment]
I did not received many request from people to add WinRT support, I can not justify making all those changes. I am sorry I will close this.

**Pull request closed without merging**
